2024-11-04 15:28:16,136 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [5455] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:28:16,149 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [5455] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:28:16,596 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [5455] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-04 15:28:16,767 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-04 15:28:16,911 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-04 15:28:16,941 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [5455] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [5455] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 returned value: None
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [5455] [MainThread] - DEBUG - ModelPath instance 2 initialized for dark_paradise.
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 returned value: None
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [5455] [MainThread] - INFO - Writing <built-in method title of str object at 0x102bda730>Path object to cache for model dark_paradise.
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [5455] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:28:21,984 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [5455] [MainThread] - DEBUG - Set key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 with value: <model_path.ModelPath object at 0x17d1f8e90>
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [5455] [MainThread] - INFO - Fetching data...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [5455] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [5455] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x17d259a90>
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [5455] [MainThread] - INFO - ModelPath instance dark_paradise found in GlobalCache. Using cached instance.
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/artifacts does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/generated does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/processed does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/reports does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/visualization does not exist. Continuing...
2024-11-04 15:28:21,985 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [5455] [MainThread] - DEBUG - ModelPath instance 3 initialized for dark_paradise.
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:28:21,986 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x17d6bf210>
2024-11-04 15:28:21,987 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [5455] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_dark_paradise.py imported successfully.
2024-11-04 15:28:21,991 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [5455] [MainThread] - INFO - Found queryset for dark_paradise in common_querysets
2024-11-04 15:28:21,991 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [5455] [MainThread] - INFO - Publishing queryset fatalities002_pgm_conflictlong
2024-11-04 15:28:21,992 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [5455] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:28:22,567 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-04 15:28:22,568 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [5455] [MainThread] - INFO - Fetching queryset fatalities002_pgm_conflictlong
2024-11-04 15:28:22,571 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [5455] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:28:37,359 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_conflictlong?start_date=121&end_date=444 HTTP/11" 200 38736950
2024-11-04 15:28:48,547 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [5455] [MainThread] - WARNING - {'dark_paradise data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:28:48\n, '}
2024-11-04 15:28:48,547 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [5455] [MainThread] - WARNING - {'dark_paradise data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:28:48\n, '}
2024-11-04 15:28:48,547 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [5455] [MainThread] - WARNING - {'dark_paradise data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:28:48\n, '}
2024-11-04 15:28:48,547 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [5455] [MainThread] - WARNING - {'dark_paradise data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:28:48\n'}
2024-11-04 15:28:48,548 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [5455] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/raw/calibration_data_fetch_log.txt
2024-11-04 15:28:48,548 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [5455] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/raw/calibration_viewser_df.pkl
2024-11-04 15:28:48,636 /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/dataloaders/get_data.py [get_data.py:12] [5455] [MainThread] - DEBUG - DataFrame shape: (4247640, 19)
2024-11-04 15:28:56,481 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [5455] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-04 15:28:56,578 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:28:56,597 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [5455] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:29:02,356 /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/management/execute_model_tasks.py [execute_model_tasks.py:56] [5455] [MainThread] - INFO - Training model dark_paradise...
2024-11-04 15:29:02,356 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [5455] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:29:02,356 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:29:02,356 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x17d3a5f90>
2024-11-04 15:29:02,356 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [5455] [MainThread] - INFO - ModelPath instance dark_paradise found in GlobalCache. Using cached instance.
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/artifacts does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/generated does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/processed does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/reports does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/visualization does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:29:02,357 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [5455] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:29:02,358 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [5455] [MainThread] - DEBUG - ModelPath instance 4 initialized for dark_paradise.
2024-11-04 15:29:02,358 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [5455] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:29:02,358 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [5455] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x17d36ee10>
2024-11-04 15:29:03,271 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [5455] [MainThread] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-04 15:33:05,077 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [5455] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:33:07,115 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [5455] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
2024-11-04 15:40:34,412 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [6051] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:40:34,427 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [6051] [MainThread] - DEBUG - Popen(['git', 'rev-parse', '--show-toplevel'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=None, shell=False, universal_newlines=False)
2024-11-04 15:40:34,871 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [6051] [Thread-1 (wrapped_target)] - DEBUG - Starting new HTTPS connection (1): api.wandb.ai:443
2024-11-04 15:40:35,075 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 1985
2024-11-04 15:40:35,223 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [Thread-1 (wrapped_target)] - DEBUG - https://api.wandb.ai:443 "POST /graphql HTTP/11" 200 393
2024-11-04 15:40:35,246 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [6051] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [6051] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 returned value: None
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [6051] [MainThread] - DEBUG - ModelPath instance 2 initialized for dark_paradise.
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 returned value: None
2024-11-04 15:40:40,126 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:340] [6051] [MainThread] - INFO - Writing <built-in method title of str object at 0x10442a7f0>Path object to cache for model dark_paradise.
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:170] [6051] [MainThread] - DEBUG - Cache saved to file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:133] [6051] [MainThread] - DEBUG - Set key: 215653327eb26d9a414feeaa36332ab5f89e337d3feb42fd4fc91aaf49c86282 with value: <model_path.ModelPath object at 0x306f2a090>
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:243] [6051] [MainThread] - INFO - Fetching data...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:37] [6051] [MainThread] - INFO - Beginning file download through viewser with month range 121,445
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [6051] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x306f7c490>
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [6051] [MainThread] - INFO - ModelPath instance dark_paradise found in GlobalCache. Using cached instance.
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/generated does not exist. Continuing...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/processed does not exist. Continuing...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/reports does not exist. Continuing...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/visualization does not exist. Continuing...
2024-11-04 15:40:40,127 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [6051] [MainThread] - DEBUG - ModelPath instance 3 initialized for dark_paradise.
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x117ba5a50>
2024-11-04 15:40:40,128 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:484] [6051] [MainThread] - INFO - Queryset /Users/dylanpinheiro/Desktop/views_pipeline/common_querysets/queryset_dark_paradise.py imported successfully.
2024-11-04 15:40:40,132 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:45] [6051] [MainThread] - INFO - Found queryset for dark_paradise in common_querysets
2024-11-04 15:40:40,132 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:208] [6051] [MainThread] - INFO - Publishing queryset fatalities002_pgm_conflictlong
2024-11-04 15:40:40,133 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [6051] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:40:40,706 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "POST /querysets/querysets?overwrite=True HTTP/11" 200 None
2024-11-04 15:40:40,706 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/viewser/commands/queryset/models/queryset.py [queryset.py:238] [6051] [MainThread] - INFO - Fetching queryset fatalities002_pgm_conflictlong
2024-11-04 15:40:40,709 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [6051] [MainThread] - DEBUG - Starting new HTTPS connection (1): viewser.viewsforecasting.org:443
2024-11-04 15:40:56,019 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [MainThread] - DEBUG - https://viewser.viewsforecasting.org:443 "GET /querysets/data/fatalities002_pgm_conflictlong?start_date=121&end_date=444 HTTP/11" 200 38736950
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [6051] [MainThread] - WARNING - {'dark_paradise data alert 1': ' alarm: feature zero; offender: ln_ged_sb_dep, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:41:07\n, '}
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [6051] [MainThread] - WARNING - {'dark_paradise data alert 2': ' alarm: feature zero; offender: ged_sb, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:41:07\n, '}
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [6051] [MainThread] - WARNING - {'dark_paradise data alert 3': ' alarm: feature zero; offender: ged_os, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:41:07\n, '}
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:56] [6051] [MainThread] - WARNING - {'dark_paradise data alert 4': ' alarm: feature zero; offender: ged_ns, threshold: 0.95 Severity: 2 Timestamp: 2024-11-04 15:41:07\n'}
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_log_files.py [utils_log_files.py:57] [6051] [MainThread] - INFO - Data fetch log file created at /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/raw/calibration_data_fetch_log.txt
2024-11-04 15:41:07,520 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/utils_dataloaders.py [utils_dataloaders.py:250] [6051] [MainThread] - INFO - Saving data to /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/raw/calibration_viewser_df.pkl
2024-11-04 15:41:07,616 /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/dataloaders/get_data.py [get_data.py:12] [6051] [MainThread] - DEBUG - DataFrame shape: (4247640, 19)
2024-11-04 15:41:13,735 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:1051] [6051] [sentry-sdk.BackgroundWorker] - DEBUG - Starting new HTTPS connection (1): o151352.ingest.sentry.io:443
2024-11-04 15:41:13,823 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:41:13,840 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/git/cmd.py [cmd.py:1253] [6051] [MainThread] - DEBUG - Popen(['git', 'cat-file', '--batch-check'], cwd=/Users/dylanpinheiro/Desktop/views_pipeline, stdin=<valid stream>, shell=False, universal_newlines=False)
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/management/execute_model_tasks.py [execute_model_tasks.py:56] [6051] [MainThread] - INFO - Training model dark_paradise...
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:304] [6051] [MainThread] - DEBUG - Model name detected: dark_paradise
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x306ae7f90>
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:322] [6051] [MainThread] - INFO - ModelPath instance dark_paradise found in GlobalCache. Using cached instance.
2024-11-04 15:41:19,618 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/generated does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/data/processed does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/reports does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/visualization does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/architectures does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/notebooks does not exist. Continuing...
2024-11-04 15:41:19,619 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:529] [6051] [MainThread] - WARNING - Directory /Users/dylanpinheiro/Desktop/views_pipeline/models/dark_paradise/src/online_evaluation does not exist. Continuing...
2024-11-04 15:41:19,620 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/model_path.py [model_path.py:258] [6051] [MainThread] - DEBUG - ModelPath instance 4 initialized for dark_paradise.
2024-11-04 15:41:19,620 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:182] [6051] [MainThread] - DEBUG - Cache loaded from file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl
2024-11-04 15:41:19,620 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:147] [6051] [MainThread] - DEBUG - Get key: eedae140563e16f6a95a2d729932837033d3c628930089d197bee472ca1f9d7e returned value: <model_path.ModelPath object at 0x306b14c90>
2024-11-04 15:41:20,508 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/darts/timeseries.py [timeseries.py:821] [6051] [MainThread] - WARNING - UserWarning: `time_col` was not set and `df` has a monotonically increasing (time) index. This results in time series groups with non-overlapping (time) index. You can ignore this warning if the index represents the actual index of each individual time series group.
2024-11-04 15:45:25,460 /Users/dylanpinheiro/miniforge3/envs/pipeline/lib/python3.11/site-packages/urllib3/connectionpool.py [connectionpool.py:546] [6051] [sentry-sdk.BackgroundWorker] - DEBUG - https://o151352.ingest.sentry.io:443 "POST /api/4504800232407040/envelope/ HTTP/11" 200 0
2024-11-04 15:45:27,501 /Users/dylanpinheiro/Desktop/views_pipeline/common_utils/global_cache.py [global_cache.py:212] [6051] [MainThread] - INFO - Cache file: /Users/dylanpinheiro/Desktop/views_pipeline/.global_cache.pkl deleted at exit
